# https://travis-ci.org/#!/jleclanche/fireplace
sudo: false
language: python
python:
  - 3.4
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python3.4
script:
  - pip install --download-cache $HOME/.pip-cache coveralls
  - ./bootstrap.sh
  - coverage run tests/test_main.py
after_script:
  - coveralls
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
